import 'dart:async';

import 'package:airplane_app/shared/shared.dart';
import 'package:airplane_app/ui/widget/widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
part 'splash_page.dart';
part 'get_started_page.dart';
part 'signup_page.dart';
part 'bonus_page.dart';
part 'main_page.dart';
part 'home_page.dart';
part 'detail_page.dart';
part 'choose_seat_page.dart';
part 'checkout_page.dart';
part 'success_checkout_page.dart';
part 'transaction_page.dart';
part 'wallet_page.dart';
part 'settings_page.dart';
